name: Ruff Job
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]
jobs:
  ruff_job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Clone PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Ruff
        run: pip install ruff

      - name: Start ruff Check
        run: ruff check --show-fixes > results.txt
        continue-on-error: true

      - name: Prepare comment file
        run: |
          echo "Результаты проверки кода этого PR с помощью ruff:" > comment.txt
          echo '```' >> comment.txt
          cat results.txt >> comment.txt
          echo '```' >> comment.txt

      - name: Send Results
        if: always()
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          path: comment.txt

      - name: Finish Job
        if: always()
        run: echo Ruff Job Has Finished